# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
