# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170803_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postType',
            new_name='post_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='typeSrc',
            new_name='type_src',
        ),
    ]
